Feat/71
Techeer-FM-Studio/frontend pull request #73
Opened 2023-04-25 04:40 UTC by TMInstaller

## 추가한 기능 설명

<br>
<img width="1223" alt="스크린샷 2023-04-25 오후 1 37 28" src="https://user-images.githubusercontent.com/54524378/234175952-aebef435-30e1-46c6-9f50-5a5e8c51c839.png">

## check list
- [ ] issue number를 브랜치 앞에 추가 하였는가?
- [ ] 모든 단위 테스트를 돌려보고 기존에 작동하던 테스트에 영향이 없는 것을 확인했는가?
- [ ] [우테코 pr 규칙](https://github.com/woowacourse/woowacourse-docs/blob/master/cleancode/pr_checklist.md)을 준수하였는가?

2023-04-25 05:18 UTC, JunJongHun requested changes

2023-04-25 05:18 UTC, JunJongHun commented on public/background.png
이 사진은 lottie에서 가져온 사진이에요~
lottie를 이용해서 애니메이션 구현해주시면 될 것 같아요! 아래 링크 달아 놓겠습니다.
[https://lottiefiles.com](https://lottiefiles.com/)

2023-04-26 18:35 UTC, TMInstaller commented on public/background.png
원본 링크 다시 알려주실 수 있으신가요?? 들어가서 찾아보았지만 저는 찾지 못하였어요..!

2023-04-27 06:30 UTC, JunJongHun approved these changes

2023-04-27 06:51 UTC, merged