Chore/89 폴더구조 리팩토링 / 코드 네이밍 컨벤션 - 메인 관련
Techeer-FM-Studio/frontend pull request #90
Opened 2023-05-29 12:13 UTC by TMInstaller

## 추가한 기능 설명

<br>

Naming convention에 맞게 변경하기

NextRoutineLayout → RoutineSpecial로 변경하고 네이밍 컨벤션 통일성 향상

- 기존 일정 중 특별한 부분을 표시하는 부분이었으므로 Special이라는 이름이 더 잘 맞는 느낌을 줌

MonthYearSelector → CalendarMonthYearSelector

- 네이밍 컨벤션 맞추기

BannerMainLayout → BannerMainSlider

- 용도에 더 잘 맞는 이름으로 변경

RoutineLayout → RoutineMain

- 위치에 더 잘 맞는 이름으로 변경

UserInfoMainLayout → UserMainInfo

- 조금더 간단하게 변경, 네이밍 컨벤션 준수

## check list

- [ ] 컴포넌트 폴더구조, 네이밍 컨벤션
- [ ] api 폴더구조, 네이밍 컨벤션
- [ ] hooks, utils 폴더구조, 네이밍 컨벤션
- [ ] style 코드 네이밍 리팩토링

2023-06-21 11:18 UTC, JunJongHun requested changes
전반적으로 잘 해주셨습니다😄

몇개 리뷰에 남긴 것 처럼 저희 컨벤션에 맞지 않은 형태들을 고쳐주시면 될 것 같습니다✏️

리펙토링 하시느라 고생 많으셨습니😄

2023-06-21 11:18 UTC, JunJongHun commented on src/components/banner/MainSlider/index.tsx
> +import BannerImage5 from '/public/temp_images/BannerTempImage5.png';
저희 컨벤션에서 이미지 관련, 정적 파일들은 `assets` 폴더에 넣기로 해서 옮겨주시면 될 것 같습니다😄

2023-06-21 11:18 UTC, JunJongHun commented on src/components/banner/MainSlider/index.tsx
> +const BannerMainSlider: React.FC<BannerMainSliderProps> = ({
저희 props의 타입을 정할 때, `BannerMainSliderPropsType`처럼 타입들은 뒤에 Type을 붙이기로 하였고, interface가 아닌 type을 사용하기로 했습니다!

React.FC를 사용해주셨는데 물론 작동하는데 문제는 없습니다! 다만 사용 용도악 조금 다른 것으로 알고 있는데요! React.FC를 사용하게 되면 children이 존재 한다고 생각 할 수 있다고 하네요! 하지만 이 컴포넌트에서는 사용되지 않네요!
참고자료 : [React.FC를 사용하지 않는 이유](https://yceffort.kr/2022/03/dont-use-react-fc)


또한 상수관련 데이터는 `constants` 폴더에 넣기로 했습니다!
물론, 이 파일에서만 사용하긴 하지만 일관성을 위해서 옮기는게 좋을 것 같습니다👍

2023-06-22 05:16 UTC, TMInstaller commented on src/components/banner/MainSlider/index.tsx
> +import BannerImage5 from '/public/temp_images/BannerTempImage5.png';
확인했습니다. 기존 public 디렉터리 삭제 후 옮기는 작업 완료입니다!

2023-06-22 05:33 UTC, TMInstaller commented on src/components/banner/MainSlider/index.tsx
> +const BannerMainSlider: React.FC<BannerMainSliderProps> = ({
넵 확인했습니다! 상수관련 데이터에 대해서는 추후에 다시 설명 요청드러야겠네요 type 관련 변경사항들은 수정 했습니다!

2023-06-22 06:45 UTC, JunJongHun approved these changes

2023-06-22 07:08 UTC, merged